### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by CyphixHL** [Dot-Rar/Envoys#1]
Installed the plugin, did a restart and it shows in /pl, and isn't working! /Envoys or /envoy says unknown command, /help envoys says nothing. I checked wiki to see if there is any dependencies but I don't see any? Please, let me know if I need to provide anything! I don't have any other plugin installed that would be interfering as well! I hope you can help me and get this to work!

Spigot: 1.8.8 

Thank you

**Comment by Dot-Rar** [comment]
Hello, are you still facing this issue?
